### Data : collection of data with different specification and have a set price range. column price_range is our target variable 
### Problem : we need to predict the Price range ,  this is a Classification problem 

### Importing the necessary libraries

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
sns.set()

### Importing the data

In [2]:
data = pd.read_csv(r"D:\Data\New folder\Mobile_Price_Range.csv")
data.head()

battery_power  bluetooth  clock_speed  dual_sim  front_camera  four_g  \
0            842          0          2.2         0             1       0   
1           1021          1          0.5         1             0       1   
2            563          1          0.5         1             2       1   
3            615          1          2.5         0             0       0   
4           1821          1          1.2         0            13       1   

   int_memory  m_depth  mobile_wt  n_cores  ...  px_height  px_width   ram  \
0           7      0.6        188        2  ...         20       756  2549   
1          53      0.7        136        3  ...        905      1988  2631   
2          41      0.9        145        5  ...       1263      1716  2603   
3          10      0.8        131        6  ...       1216      1786  2769   
4          44      0.6        141        2  ...       1208      1212  1411   

   screen_height  screen_weight  talk_time_battery  three_g  touch_screen  \
0              9              7                 19        0             0   
1             17              3                  7        1             1   
2             11              2                  9        1             1   
3             16              8                 11        1             0   
4              8              2                 15        1             1   

   wifi  price_range  
0     1            1  
1     0            2  
2     0            2  
3     0            2  
4     0            1  

[5 rows x 21 columns]

In [3]:
data.describe()

battery_power  bluetooth  clock_speed     dual_sim  front_camera  \
count    2000.000000  2000.0000  2000.000000  2000.000000   2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500      4.309500   
std       439.418206     0.5001     0.816004     0.500035      4.341444   
min       501.000000     0.0000     0.500000     0.000000      0.000000   
25%       851.750000     0.0000     0.700000     0.000000      1.000000   
50%      1226.000000     0.0000     1.500000     1.000000      3.000000   
75%      1615.250000     1.0000     2.200000     1.000000      7.000000   
max      1998.000000     1.0000     3.000000     1.000000     19.000000   

            four_g   int_memory      m_depth    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram  screen_height  screen_weight  \
count  2000.000000  2000.000000  2000.000000    2000.000000    2000.000000   
mean    645.108000  1251.515500  2124.213000      12.306500       5.767000   
std     443.780811   432.199447  1084.732044       4.213245       4.356398   
min       0.000000   500.000000   256.000000       5.000000       0.000000   
25%     282.750000   874.750000  1207.500000       9.000000       2.000000   
50%     564.000000  1247.000000  2146.500000      12.000000       5.000000   
75%     947.250000  1633.000000  3064.500000      16.000000       9.000000   
max    1960.000000  1998.000000  3998.000000      19.000000      18.000000   

       talk_time_battery      three_g  touch_screen         wifi  price_range  
count        2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean           11.011000     0.761500      0.503000     0.507000     1.500000  
std             5.463955     0.426273      0.500116     0.500076     1.118314  
min             2.000000     0.000000      0.000000     0.000000     0.000000  
25%             6.000000     1.000000      0.000000     0.000000     0.750000  
50%            11.000000     1.000000      1.000000     1.000000     1.500000  
75%            16.000000     1.000000      1.000000     1.000000     2.250000  
max            20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
battery_power        2000 non-null int64
bluetooth            2000 non-null int64
clock_speed          2000 non-null float64
dual_sim             2000 non-null int64
front_camera         2000 non-null int64
four_g               2000 non-null int64
int_memory           2000 non-null int64
m_depth              2000 non-null float64
mobile_wt            2000 non-null int64
n_cores              2000 non-null int64
primary_camera       2000 non-null int64
px_height            2000 non-null int64
px_width             2000 non-null int64
ram                  2000 non-null int64
screen_height        2000 non-null int64
screen_weight        2000 non-null int64
talk_time_battery    2000 non-null int64
three_g              2000 non-null int64
touch_screen         2000 non-null int64
wifi                 2000 non-null int64
price_range          2000 non-null int64
dtypes: float64(2), int64(19

### Feature selection through SelectKBest

In [5]:
X = data.iloc[:,0:20]
y = data.iloc[:,-1]

In [6]:
bestfeatures = SelectKBest(score_func=chi2, k=12)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
featureScores = pd.concat ([dfcolumns,dfscores], axis=1)
featureScores.columns = ['Specs','Score']
print(featureScores.nlargest(12,'Score'))

                Specs          Score
13                ram  931267.519053
11          px_height   17363.569536
0       battery_power   14129.866576
12           px_width    9810.586750
8           mobile_wt      95.972863
6          int_memory      89.839124
15      screen_weight      16.480319
16  talk_time_battery      13.236400
4        front_camera      10.135166
14      screen_height       9.614878
10     primary_camera       9.186054
9             n_cores       9.097556


In [7]:
new = featureScores.nlargest(12,'Score')

In [8]:
new.Specs.values

array(['ram', 'px_height', 'battery_power', 'px_width', 'mobile_wt',
       'int_memory', 'screen_weight', 'talk_time_battery', 'front_camera',
       'screen_height', 'primary_camera', 'n_cores'], dtype=object)

In [9]:
cols = ['ram', 'px_height', 'battery_power', 'px_width', 'mobile_wt',
       'int_memory', 'screen_weight', 'talk_time_battery', 'front_camera',
       'screen_height', 'primary_camera', 'n_cores','price_range']

In [10]:
new_data = data[cols]

In [11]:
new_data.head()

ram  px_height  battery_power  px_width  mobile_wt  int_memory  \
0  2549         20            842       756        188           7   
1  2631        905           1021      1988        136          53   
2  2603       1263            563      1716        145          41   
3  2769       1216            615      1786        131          10   
4  1411       1208           1821      1212        141          44   

   screen_weight  talk_time_battery  front_camera  screen_height  \
0              7                 19             1              9   
1              3                  7             0             17   
2              2                  9             2             11   
3              8                 11             0             16   
4              2                 15            13              8   

   primary_camera  n_cores  price_range  
0               2        2            1  
1               6        3            2  
2               6        5            2  
3               9        6            2  
4              14        2            1

### Spliting data into Input and target

In [16]:
input = new_data.iloc[:,0:12]
target = new_data.iloc[:,-1]

### Normalizing data

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#scaler.fit(X)
x_scaled = scaler.fit_transform(input)

### Spliting data into training and testing 

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled,target , test_size=0.20, random_state=42)

### Creating Logistic Regression Model

In [20]:
model = LogisticRegression(solver='lbfgs',multi_class='auto')
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

### Testing the model on unknown data

In [21]:
y_pred = model.predict(X_test)

### accuracy of the model

In [22]:
print(model.score(X_test,y_test))

0.985


In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[104   1   0   0]
 [  0  91   0   0]
 [  0   2  88   2]
 [  0   0   1 111]]


In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       105
           1       0.97      1.00      0.98        91
           2       0.99      0.96      0.97        92
           3       0.98      0.99      0.99       112

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.99      0.98      0.98       400

